### ISSUE TITLE
How does the database keep track of edits?

### ISSUE THREAD

**Issue by Bibilidibipi** [matthewsymonds/capstone-project-proposal#3]
Does each edit create a new article with modified content? If so, how do you keep track of which version of an article is the most recent?

**Comment by matthewsymonds** [comment]
First take: current article will store most recent body. previous edits will store the whole article body.

Bonus: current article will store most recent body. Previous edits will be stored as diffs, which can be applied to the article body to move it backward.

**Comment by matthewsymonds** [comment]
Added a "content" column to the schema to indicate either the article or the diff.
